/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

/**
 *
 * @author Melany
 */
public class ContactoT2Frame extends javax.swing.JFrame {

    /**
     * Creates new form ContactoT1Frame
     */
    public ContactoT2Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlabel_nombre = new javax.swing.JLabel();
        Jlabel_titulo = new javax.swing.JLabel();
        face_txt = new javax.swing.JTextField();
        Jlabel_Edad = new javax.swing.JLabel();
        nacimiento_txt = new javax.swing.JTextField();
        Jlabel_Genero = new javax.swing.JLabel();
        genero_txt = new javax.swing.JTextField();
        Jlabel_Direccion = new javax.swing.JLabel();
        direccion_txt = new javax.swing.JTextField();
        Jlabel_Direccion1 = new javax.swing.JLabel();
        telefono_txt = new javax.swing.JTextField();
        Jlabel_titulo1 = new javax.swing.JLabel();
        Jlabel_instagram = new javax.swing.JLabel();
        Jlabel_facebook1 = new javax.swing.JLabel();
        Jlabel_twitter = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        insta_txt = new javax.swing.JTextField();
        twi_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda - Contacto Tipo 2");
        setLocation(new java.awt.Point(500, 200));

        Jlabel_nombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_nombre.setText("Nombre:");

        Jlabel_titulo.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        Jlabel_titulo.setText("Contacto Tipo 2");

        face_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        face_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                face_txtActionPerformed(evt);
            }
        });

        Jlabel_Edad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_Edad.setText("Nacimiento:");

        nacimiento_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        nacimiento_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacimiento_txtActionPerformed(evt);
            }
        });

        Jlabel_Genero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_Genero.setText("Genero:");

        genero_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N

        Jlabel_Direccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_Direccion.setText("Dirección:");

        direccion_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N

        Jlabel_Direccion1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_Direccion1.setText("Teléfono:");

        telefono_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N

        Jlabel_titulo1.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        Jlabel_titulo1.setText("Redes Sociales");

        Jlabel_instagram.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_instagram.setText("Instagram:");

        Jlabel_facebook1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_facebook1.setText("Facebook:");

        Jlabel_twitter.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_twitter.setText("Twitter:");

        nombre_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_txtActionPerformed(evt);
            }
        });

        insta_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        insta_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insta_txtActionPerformed(evt);
            }
        });

        twi_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        twi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twi_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(Jlabel_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Jlabel_Direccion1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabel_Edad)
                            .addComponent(Jlabel_Genero)
                            .addComponent(Jlabel_Direccion)
                            .addComponent(Jlabel_nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(direccion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(Jlabel_twitter))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genero_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(Jlabel_instagram))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nacimiento_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(Jlabel_facebook1))
                            .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(face_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insta_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Jlabel_titulo1)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Jlabel_titulo)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jlabel_titulo1))
                    .addComponent(Jlabel_nombre))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_facebook1)
                    .addComponent(nacimiento_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlabel_Edad)
                    .addComponent(face_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_instagram)
                    .addComponent(Jlabel_Genero)
                    .addComponent(genero_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insta_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(direccion_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jlabel_Direccion))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jlabel_twitter)
                        .addComponent(twi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlabel_Direccion1))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void face_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_face_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_face_txtActionPerformed

    private void nacimiento_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacimiento_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacimiento_txtActionPerformed

    private void nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_txtActionPerformed

    private void insta_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insta_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insta_txtActionPerformed

    private void twi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twi_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactoT2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactoT2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactoT2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactoT2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactoT2Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_Direccion;
    private javax.swing.JLabel Jlabel_Direccion1;
    private javax.swing.JLabel Jlabel_Edad;
    private javax.swing.JLabel Jlabel_Genero;
    private javax.swing.JLabel Jlabel_facebook1;
    private javax.swing.JLabel Jlabel_instagram;
    private javax.swing.JLabel Jlabel_nombre;
    private javax.swing.JLabel Jlabel_titulo;
    private javax.swing.JLabel Jlabel_titulo1;
    private javax.swing.JLabel Jlabel_twitter;
    public javax.swing.JTextField direccion_txt;
    public javax.swing.JTextField face_txt;
    public javax.swing.JTextField genero_txt;
    public javax.swing.JTextField insta_txt;
    public javax.swing.JTextField nacimiento_txt;
    public javax.swing.JTextField nombre_txt;
    public javax.swing.JTextField telefono_txt;
    public javax.swing.JTextField twi_txt;
    // End of variables declaration//GEN-END:variables
}
