/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

/**
 *
 * @author Melany
 */
public class EventoT1Frame extends javax.swing.JFrame {

    /**
     * Creates new form EventoT1Frame
     */
    public EventoT1Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_txt = new javax.swing.JTextField();
        Jlabel_titulo2 = new javax.swing.JLabel();
        Jlabel_asunto = new javax.swing.JLabel();
        Jlabel_jornada = new javax.swing.JLabel();
        Jlabel_fecha = new javax.swing.JLabel();
        Jlabel_limportancia = new javax.swing.JLabel();
        Jlabel_lugar1 = new javax.swing.JLabel();
        importancia_txt = new javax.swing.JTextField();
        lugar_txt = new javax.swing.JTextField();
        fecha_txt = new javax.swing.JTextField();
        asunto_txt = new javax.swing.JTextField();
        jornada_txt2 = new javax.swing.JTextField();

        nombre_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_txtActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda - Eventos Tipo 1");

        Jlabel_titulo2.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        Jlabel_titulo2.setText("Evento Tipo 1");

        Jlabel_asunto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_asunto.setText("Asunto:");

        Jlabel_jornada.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_jornada.setText("Jornada:");

        Jlabel_fecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_fecha.setText("Fecha:");

        Jlabel_limportancia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_limportancia.setText("Importancia:");

        Jlabel_lugar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_lugar1.setText("Lugar:");

        importancia_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        importancia_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importancia_txtActionPerformed(evt);
            }
        });

        lugar_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        lugar_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar_txtActionPerformed(evt);
            }
        });

        fecha_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        fecha_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_txtActionPerformed(evt);
            }
        });

        asunto_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        asunto_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asunto_txtActionPerformed(evt);
            }
        });

        jornada_txt2.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jornada_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jornada_txt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(Jlabel_titulo2)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlabel_lugar1)
                        .addGap(58, 58, 58)
                        .addComponent(lugar_txt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlabel_limportancia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(importancia_txt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlabel_fecha)
                        .addGap(51, 51, 51)
                        .addComponent(fecha_txt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlabel_jornada)
                        .addGap(38, 38, 38)
                        .addComponent(jornada_txt2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlabel_asunto)
                        .addGap(46, 46, 46)
                        .addComponent(asunto_txt)))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Jlabel_titulo2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_asunto)
                    .addComponent(asunto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_fecha)
                    .addComponent(fecha_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_jornada)
                    .addComponent(jornada_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_lugar1)
                    .addComponent(lugar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_limportancia)
                    .addComponent(importancia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_txtActionPerformed

    private void importancia_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importancia_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importancia_txtActionPerformed

    private void lugar_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugar_txtActionPerformed

    private void fecha_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_txtActionPerformed

    private void asunto_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asunto_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asunto_txtActionPerformed

    private void jornada_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jornada_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jornada_txt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventoT1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventoT1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventoT1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventoT1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventoT1Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_asunto;
    private javax.swing.JLabel Jlabel_fecha;
    private javax.swing.JLabel Jlabel_jornada;
    private javax.swing.JLabel Jlabel_limportancia;
    private javax.swing.JLabel Jlabel_lugar1;
    private javax.swing.JLabel Jlabel_titulo2;
    public javax.swing.JTextField asunto_txt;
    public javax.swing.JTextField fecha_txt;
    public javax.swing.JTextField importancia_txt;
    public javax.swing.JTextField jornada_txt2;
    public javax.swing.JTextField lugar_txt;
    public javax.swing.JTextField nombre_txt;
    // End of variables declaration//GEN-END:variables
}
