/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

/**
 *
 * @author Melany
 */
public class EventoT2Frame extends javax.swing.JFrame {

    /**
     * Creates new form EventoT1Frame
     */
    public EventoT2Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_txt = new javax.swing.JTextField();
        Jlabel_titulo2 = new javax.swing.JLabel();
        Jlabel_asunto = new javax.swing.JLabel();
        Jlabel_jornada = new javax.swing.JLabel();
        Jlabel_fecha = new javax.swing.JLabel();
        Jlabel_lugar1 = new javax.swing.JLabel();
        lugar_txt = new javax.swing.JTextField();
        fecha_txt = new javax.swing.JTextField();
        pagina_txt = new javax.swing.JTextField();
        jornada_txt2 = new javax.swing.JTextField();
        Jlabel_titulo3 = new javax.swing.JLabel();
        Jlabel_asunto1 = new javax.swing.JLabel();
        Jlabel_asunto2 = new javax.swing.JLabel();
        oficina_txt = new javax.swing.JTextField();
        asunto_txt = new javax.swing.JTextField();

        nombre_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_txtActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda - Eventos Tipo 2");

        Jlabel_titulo2.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        Jlabel_titulo2.setText("Evento Tipo 2");

        Jlabel_asunto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_asunto.setText("Asunto:");

        Jlabel_jornada.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_jornada.setText("Jornada:");

        Jlabel_fecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_fecha.setText("Fecha:");

        Jlabel_lugar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_lugar1.setText("Lugar:");

        lugar_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        lugar_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar_txtActionPerformed(evt);
            }
        });

        fecha_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        fecha_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_txtActionPerformed(evt);
            }
        });

        pagina_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        pagina_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagina_txtActionPerformed(evt);
            }
        });

        jornada_txt2.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jornada_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jornada_txt2ActionPerformed(evt);
            }
        });

        Jlabel_titulo3.setFont(new java.awt.Font("Century Gothic", 3, 16)); // NOI18N
        Jlabel_titulo3.setText("Información Empresa");

        Jlabel_asunto1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_asunto1.setText("Página Web:");

        Jlabel_asunto2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Jlabel_asunto2.setText("Teléfono Oficina:");

        oficina_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        oficina_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oficina_txtActionPerformed(evt);
            }
        });

        asunto_txt.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        asunto_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asunto_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlabel_lugar1)
                        .addGap(58, 58, 58)
                        .addComponent(lugar_txt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlabel_jornada)
                        .addGap(38, 38, 38)
                        .addComponent(jornada_txt2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabel_fecha)
                            .addComponent(Jlabel_asunto))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asunto_txt))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jlabel_titulo3)
                        .addGap(153, 153, 153))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabel_asunto2)
                            .addComponent(Jlabel_asunto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pagina_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oficina_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(62, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jlabel_titulo2)
                .addGap(352, 352, 352))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Jlabel_titulo2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jlabel_asunto)
                            .addComponent(asunto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Jlabel_titulo3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_fecha)
                    .addComponent(fecha_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlabel_asunto1)
                    .addComponent(pagina_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_jornada)
                    .addComponent(jornada_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlabel_asunto2)
                    .addComponent(oficina_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel_lugar1)
                    .addComponent(lugar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_txtActionPerformed

    private void lugar_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugar_txtActionPerformed

    private void fecha_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_txtActionPerformed

    private void pagina_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagina_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagina_txtActionPerformed

    private void jornada_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jornada_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jornada_txt2ActionPerformed

    private void oficina_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oficina_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oficina_txtActionPerformed

    private void asunto_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asunto_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asunto_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventoT2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventoT2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventoT2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventoT2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventoT2Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_asunto;
    private javax.swing.JLabel Jlabel_asunto1;
    private javax.swing.JLabel Jlabel_asunto2;
    private javax.swing.JLabel Jlabel_fecha;
    private javax.swing.JLabel Jlabel_jornada;
    private javax.swing.JLabel Jlabel_lugar1;
    private javax.swing.JLabel Jlabel_titulo2;
    private javax.swing.JLabel Jlabel_titulo3;
    public javax.swing.JTextField asunto_txt;
    public javax.swing.JTextField fecha_txt;
    public javax.swing.JTextField jornada_txt2;
    public javax.swing.JTextField lugar_txt;
    public javax.swing.JTextField nombre_txt;
    public javax.swing.JTextField oficina_txt;
    public javax.swing.JTextField pagina_txt;
    // End of variables declaration//GEN-END:variables
}
